import collections
from nem.util import reverse_dict


_metagenres = {
    'indie': ['art pop',
        'melancholia',
        'modern rock',
        'indie pop',
        'indie rock',
        'freak folk',
        'dream pop',
        'garage psych',
        'canadian indie',
        'modern alternative rock',
        'chillwave'],
    'lounge': ['adult standards',
        'lounge',
        'vocal jazz',
        'swing',
        'classic uk pop',
        'brill building pop',
        'bubblegum pop',
        'big band',
        'rock-and-roll',
        'easy listening',
        'stride'],
    'soft rock/pop': ['pop rock', 'neo mellow', 'acoustic pop', 'opm'],
    'r&b, soul, funk': ['hip pop',
        'contemporary r&b',
        'neo soul',
        'quiet storm',
        'r&b',
        'urban contemporary',
        'soul',
        'motown',
        'classic soul',
        'disco',
        'funk',
        'southern soul'],
    'punk': ['alternative rock',
        'punk',
        'skate punk',
        'experimental',
        'gbvfi',
        'post-punk',
        'punk blues'],
    'rap & hip-hop': ['pop rap',
        'hip hop',
        'gangster rap',
        'rap',
        'dirty south rap',
        'southern hip hop',
        'trap',
        'vapor trap',
        'alternative hip hop',
        'east coast hip hop',
        'underground hip hop',
        'hardcore hip hop',
        'turntablism',
        'underground rap'],
    'folk': ['folk',
        'roots rock',
        'singer-songwriter',
        'lilith',
        'indie folk',
        'alternative country',
        'texas country',
        'stomp and holler',
        'new americana',
        'deep new americana'],
    'classical': ['classical',
        'renaissance',
        'post-romantic era',
        'baroque',
        'early music',
        'early modern classical'],
    'show tunes': ['broadway', 'show tunes', 'hollywood'],
    'metal': ['alternative metal',
        'nu metal',
        'rap rock',
        'metal',
        'industrial metal',
        'death metal',
        'post-doom metal'],
    'edm': ['vocal house',
        'edm',
        'future bass',
        'pop edm',
        'disco house',
        'melodic dubstep',
        'electro house',
        'deep house',
        'house',
        'pop dance',
        'tropical house',
        'progressive house',
        'gaming edm',
        'dubstep',
        'gaming dubstep',
        'electronic trap'],
    'metalcore': ['pop punk',
        'emo',
        'screamo',
        'bubblegrunge',
        'indie punk',
        'post-hardcore',
        'melodic metalcore',
        'metalcore',
        'dreamo'],
    'new wave': ['europop',
        'new wave pop',
        'permanent wave',
        'new wave',
        'new romantic',
        'synthpop'],
    'rock': ['rock',
        'album rock',
        'classic rock',
        'mellow gold',
        'soft rock',
        'folk rock',
        'hard rock',
        'art rock',
        'symphonic rock',
        'glam metal',
        'psychedelic rock'],
    'contemporary classical': ['american contemporary classical',
        'contemporary classical',
        'avant-garde',
        '21st century classical'],
    'alternative r&b': ['escape room', 'alternative r&b', 'indie soul'],  # https://www.thefader.com/2020/12/02/escape-room-genre-spotify-unwrapped-explanation-every-noise-glenn-mcdonald
    'techno': ['alternative dance',
        'electronica',
        'microhouse',
        'minimal techno',
        'new rave',
        'tech house'],
    'drum and bass': ['drum and bass'],
    'afropop': ['afropop'],
    'christian': ['christian music', 'christian alternative rock'],
    'new age': ['new age', 'new age piano'],
    'latin': ['latin',
        'latin pop',
        'ranchera',
        'latin alternative',
        'rock en espanol',
        'tropical',
        'latin hip hop',
        'reggaeton'],
    'soundtrack': ['scorecore', 'soundtrack', 'video game music'],
    'blues': ['blues',
        'blues rock',
        'electric blues',
        'modern blues',
        'modern blues rock',
        'traditional blues'],
    'reggae': ['dub', 'reggae', 'roots reggae', 'ska', 'lovers rock'],
    'jazz': ['jazz',
        'contemporary jazz',
        'jazz fusion',
        'smooth jazz',
        'jazz saxophone'],
    'country': ['country', 'contemporary country', 'country road'],
    'pop': ['dance pop', 'pop', 'post-teen pop', 'electropop', 'indie poptimism'],
    'irish': ['celtic', 'irish folk'],
    'bluegrass': ['appalachian folk',
        'banjo',
        'bluegrass',
        'old-time',
        'progressive bluegrass'],
    'lofi': ['chillhop', 'lo-fi beats'],
    'ambient': ['ambient', 'compositional ambient']
}


_metagenres_fine = {
  'metal': ['metal',
     'slayer',
     'speed metal',
     'us power metal',
     'voidgrind',
     'instrumental rock',
     'neo classical metal',
     'power metal',
     'shred',
     'death metal',
     'melodic death metal',
     'swedish death metal',
     'swedish metal',
     'technical death metal',
     'gothic symphonic metal',
     'black metal',
     'gothic metal',
     'symphonic black metal',
     'german metal',
     'melodic metal',
     'neo-trad metal',
     'symphonic metal',
     'brutal death metal',
     'florida death metal',
     'old school thrash',
     'crossover thrash',
     'thrash metal',
     'symphonic death metal',
     'atmospheric black metal',
     'usbm',
     'avant-garde metal',
     'deathrash',
     'finnish metal',
     'folk metal',
     'nwothm',
     'norwegian black metal',
     'norwegian metal',
     'pagan black metal',
     'black thrash',
     'dark black metal',
     'deathgrind',
     'grindcore',
     'jazz metal',
     'voidgaze',
     'post-black metal',
     'progressive jazz fusion',
     'symphonic power metal',
     'nyc metal',
     'australian metal',
     'death doom',
     'cavernous death metal',
     'black death'],
 'soundtrack': ['classic soundtrack',
     'scorecore',
     'soundtrack',
     'british soundtrack',
     'hauntology',
     'theme',
     'video game music',
     'light music',
     'epicore',
     'japanese vgm',
     'japanese classical',
     'indie game soundtrack',
     'library music'],
 'nu metal': ['alternative metal',
     'funk metal',
     'nu metal',
     'rap metal',
     'rap rock',
     'christian metal',
     'christian punk',
     'christian rock',
     'deep christian rock',
     'post-grunge',
     'funk rock',
     'groove metal',
     'melodic metalcore',
     'metalcore',
     'grunge pop',
     'hard alternative',
     'christian hardcore',
     'deathcore',
     'djent',
     'gymcore',
     'post-screamo'],
 'rock': ['rock',
     'album rock',
     'classic rock',
     'mellow gold',
     'soft rock',
     'yacht rock',
     'new wave pop',
     'classic canadian rock',
     'permanent wave',
     'new wave',
     'britpop',
     'dance rock',
     'hard rock',
     'art rock',
     'experimental',
     'experimental rock',
     'noise rock',
     'post-punk',
     'new romantic',
     'heartland rock',
     'sophisti-pop',
     'synthpop',
     'classic uk pop',
     'glam metal',
     'sleaze rock',
     'supergroup',
     'modern hard rock',
     'deep soft rock',
     'canadian metal',
     'solo wave',
     'beatlesque',
     'uk post-punk',
     'melodic hard rock',
     'glam rock',
     'zolo',
     'welsh indie',
     'noise punk'],
 'folk': ['canadian singer-songwriter',
     'folk',
     'folk rock',
     'roots rock',
     'singer-songwriter',
     'ectofolk',
     'lilith',
     "women's music",
     'outlaw country',
     'austin singer-songwriter',
     'indie folk',
     'alternative country',
     'texas country',
     'stomp and holler',
     'contemporary folk',
     'southern rock',
     'canadian rock',
     'new americana',
     'alternative americana',
     'deep acoustic pop',
     'folk-pop',
     'american folk revival',
     'cosmic american',
     'deep new americana',
     'canadian folk',
     'canadian indie',
     'modern folk rock',
     'toronto indie',
     'red dirt',
     'roots americana',
     'alternative roots rock',
     'new england americana',
     'modern southern rock',
     'canadian celtic',
     'michigan indie',
     'canadian americana',
     'quebec indie',
     'nl folk',
     'canadian country',
     'north carolina roots',
     'indie anthem-folk'],
 'latin': ['latin',
     'latin pop',
     'mariachi',
     'ranchera',
     'regional mexican',
     'latin jazz',
     'mexican pop',
     'bolero',
     'latin arena pop',
     'salsa',
     'tropical',
     'dominican pop',
     'trap latino',
     'salsa puertorriquena',
     'italian adult pop',
     'merengue',
     'latin hip hop',
     'reggaeton',
     'musica tradicional cubana',
     'salsa international',
     'mexican rock-and-roll',
     'bachata',
     'cumbia',
     'reggaeton flow'],
 'indie': ['alternative rock',
     'art pop',
     'melancholia',
     'anti-folk',
     'indie pop',
     'indie rock',
     'chamber pop',
     'freak folk',
     'grunge',
     'lo-fi',
     'riot grrrl',
     'olympia wa indie',
     'dream pop',
     'garage psych',
     'gbvfi',
     'nu gaze',
     'shoegaze',
     'new jersey indie',
     'modern dream pop',
     'experimental pop',
     'portland indie',
     'alternative pop',
     'jangle pop',
     'power pop',
     'underground power pop',
     'electra',
     'folk punk',
     'modern power pop',
     'noise pop',
     'elephant 6',
     'neo-psychedelic',
     'boston rock',
     'pub rock',
     'baroque pop',
     'athens indie',
     'chillwave',
     'chamber psych',
     'slowcore',
     'folktronica',
     'american shoegaze',
     'bay area indie',
     'indie shoegaze',
     'indie garage rock',
     'brooklyn indie',
     'popgaze',
     'small room',
     'indie dream pop',
     'bedroom pop'],
 'reggae': ['ska punk',
     'soca',
     'dub',
     'reggae',
     'roots reggae',
     'dancehall',
     'reggae fusion',
     'ska',
     'lovers rock',
     'rocksteady',
     'ska revival',
     'modern ska punk',
     'traditional ska',
     'hawaiian',
     'slack-key guitar',
     'old school dancehall',
     'reggae rock',
     'modern reggae',
     'jawaiian',
     'deep ragga'],
 'hip hop': ['conscious hip hop',
     'political hip hop',
     'pop rap',
     'hip hop',
     'chicano rap',
     'gangster rap',
     'rap',
     'west coast rap',
     'houston rap',
     'dirty south rap',
     'southern hip hop',
     'trap',
     'vapor trap',
     'alternative hip hop',
     'east coast hip hop',
     'nyc rap',
     'queens hip hop',
     'underground hip hop',
     'atl hip hop',
     'melodic rap',
     'crunk',
     'deep southern trap',
     'dirty texas rap',
     'boom bap',
     'golden age hip hop',
     'old school hip hop',
     'dark trap',
     'hardcore hip hop',
     'jazz rap',
     'g funk',
     'hyphy',
     'oakland hip hop',
     'abstract hip hop',
     'turntablism',
     'bronx hip hop',
     'wu fam',
     'chicago rap',
     'electro',
     'bass music',
     'miami bass',
     'miami hip hop',
     'cali rap',
     'minnesota hip hop',
     'underground rap',
     'west coast trap',
     'new jersey rap',
     'detroit hip hop',
     'battle rap',
     'scratch',
     'memphis hip hop',
     'sad rap',
     'experimental hip hop',
     'emo rap',
     'meme rap',
     'indie hip hop',
     'atl trap'],
 'world / meditation': ['healing',
     'meditation',
     'native american',
     'arab folk',
     'world fusion',
     'kirtan',
     'indian classical',
     'coverchill',
     'shamanic',
     'persian alternative'],
 'gospel': ['gospel', 'christian hip hop', 'christian trap'],
 'punk': ['punk',
      'skate punk',
      'vancouver indie',
      'hardcore',
      'garage rock',
      'punk blues',
      'hardcore punk',
      'nyhc',
      'power-pop punk',
      'chicago punk',
      'detroit rock',
      'garage pop',
      'crust punk',
      "punk 'n' roll",
      'melodic hardcore',
      'straight edge',
      'canadian punk',
      'oi',
      'vancouver punk',
      'american oi',
      'orgcore',
      'thrash core',
      'garage punk',
      'skinhead oi'],
 'techno': ['german electronica',
      'indie electronica',
      'breakcore',
      'drill and bass',
      'german techno',
      'ambient idm',
      'deep idm',
      'microhouse',
      'minimal techno',
      'intelligent dance music',
      'tech house',
      'dub techno',
      'cologne electronic',
      'float house',
      'pop ambient',
      'hamburg electronic',
      'minimal tech house',
      'deep disco house',
      'outsider house',
      'techno',
      'organic house',
      'minimal dub',
      'abstract idm'],
 'trip hop': ['big beat',
      'breakbeat',
      'alternative dance',
      'electronica',
      'new rave',
      'trip hop',
      'downtempo',
      'nu skool breaks',
      'electroclash',
      'ninja',
      'nu jazz',
      'nu disco',
      'balearic',
      'electro jazz',
      'chill lounge',
      'new french touch',
      'dance-punk',
      'filter house'],
 'goa': ['full on',
      'progressive psytrance',
      'psychedelic trance',
      'psychill',
      'deep ambient',
      'space ambient',
      'ambient psychill',
      'goa trance'],
 15: ['protopunk',
      'brill building pop',
      'bubblegum pop',
      'psychedelic rock',
      'psychobilly',
      'rockabilly',
      'instrumental surf',
      'rock-and-roll',
      'rhythm and blues',
      'british invasion',
      'deep surf music',
      'surf music',
      'horror punk',
      'doo-wop',
      'merseybeat',
      'classic garage rock',
      'freakbeat'],
 'jazz': ['jazz',
      'contemporary jazz',
      'avant-garde jazz',
      'free improvisation',
      'free jazz',
      'japanese jazz',
      'electric bass',
      'jazz fusion',
      'jazz organ',
      'bebop',
      'hard bop',
      'jazz drums',
      'instrumental funk',
      'jazz funk',
      'modern funk',
      'afrofuturism',
      'jazz saxophone',
      'jazz guitar',
      'jazz piano',
      'contemporary post-bop',
      'cool jazz',
      'jazz double bass',
      'jazz violin',
      'gypsy jazz',
      'swedish jazz',
      'modern jazz piano',
      'soul jazz',
      'jazz vibraphone',
      'ecm-style jazz',
      'spiritual jazz',
      'jazz trio',
      'rare groove'],
 'ambient': ['ambient',
      'post-rock',
      'escape room',
      'nu age',
      'glitch',
      'drone',
      'sound art',
      'compositional ambient',
      'fourth world',
      'new isolationism',
      'warm drone',
      'american post-rock',
      'drift',
      'j-ambient',
      'instrumental post-rock',
      'glitchcore',
      'experimental ambient',
      'hyperpop',
      'neo-classical',
      'mandible',
      'deconstructed club'],
 'celtic': ['british folk',
      'bagpipe',
      'celtic',
      'celtic rock',
      'irish folk',
      'jig and reel',
      'irish neo-traditional',
      'scottish folk',
      'irish fiddle',
      'traditional irish singing',
      'uilleann pipes',
      'shanty',
      'traditional british folk',
      'celtic punk'],
 'trap soul': ['indie jazz',
      'canadian contemporary r&b',
      'alternative r&b',
      'chill r&b',
      'indie r&b',
      'indie soul',
      'canadian hip hop',
      'canadian pop',
      'uk contemporary jazz',
      'trap soul'],
 'industrial': ['cyberpunk',
      'industrial',
      'industrial metal',
      'industrial rock',
      'neo-synthpop',
      'dark electro',
      'futurepop',
      'ebm',
      'electro-industrial',
      'deep neo-synthpop',
      'aggrotech',
      'synthwave',
      'dark clubbing',
      'danish electro',
      'swedish synthpop',
      'power noise'],
 'australian': ['australian alternative rock',
      'australian rock',
      'australian dance',
      'australian pop',
      'australian indie',
      'australian indigenous'],
 'nerd': ['nerdcore', 'comedy', 'comic', 'geek rock', 'geek folk', 'neo-pagan'],
 'grime': ['grime', 'uk hip hop', 'uk alternative hip hop'],
 'j-rock': ['j-pop', 'otacore', 'j-metal', 'j-rock', 'anime', 'j-poprock'],
 'bluegrass': ['neo-traditional bluegrass',
      'appalachian folk',
      'banjo',
      'bluegrass',
      'bluegrass gospel',
      'mandolin',
      'old-time',
      'progressive bluegrass',
      'jam band',
      'instrumental bluegrass',
      'old-time fiddle',
      'traditional folk',
      'traditional bluegrass',
      'country gospel',
      'cowboy western',
      'traditional country',
      'vintage old-time',
      'vintage country folk',
      'string band',
      'traditional southern folk',
      'modern old-time'],
 'modern classical': ['american 21st century classical',
      'american modern classical',
      'american contemporary classical',
      'contemporary classical',
      'british contemporary classical',
      'minimalism',
      'acousmatic',
      'avant-garde',
      'concert band',
      'nordic contemporary classical',
      'laboratorio',
      'experimental guitar',
      'serialism',
      'post-minimalism',
      '21st century classical',
      'african-american classical',
      'tzadik',
      'baltic classical',
      'american romanticism',
      'canadian classical',
      'danish contemporary classical'],
 'easteuropean': ['classic swedish pop',
      'swedish pop',
      'russian alt pop',
      'eurovision',
      'russian hip hop',
      'russian dance pop',
      'russian pop',
      'ukrainian pop',
      'russian rock'],
 'edm': ['edm',
      'chillstep',
      'future bass',
      'pop edm',
      'melodic dubstep',
      'bass trap',
      'electro house',
      'traprun',
      'brostep',
      'complextro',
      'house',
      'vapor twitch',
      'pop dance',
      'tropical house',
      'progressive house',
      'uplifting trance',
      'gaming edm',
      'kawaii future bass',
      'progressive electro house',
      'bass house',
      'progressive trance',
      'slap house',
      'deep groove house',
      'dutch edm',
      'dubstep',
      'riddim dubstep',
      'gaming dubstep',
      'classic progressive house',
      'trance',
      'uk dance',
      'electronic trap',
      'filthstep',
      'canadian electronic'],
 'pop': ['dance pop',
      'modern rock',
      'pop',
      'post-teen pop',
      'electropop',
      'metropopolis',
      'social media pop',
      'austindie',
      'indie poptimism',
      'modern alternative rock',
      'vapor soul',
      'uk pop',
      'indietronica',
      'la indie',
      'shimmer pop',
      'la pop',
      'stomp pop',
      'alt z',
      'etherpop',
      'indie electropop'],
 'stoner rock': ['dub metal',
      'sludge metal',
      'stoner metal',
      'stoner rock',
      'drone metal',
      'doom metal',
      'gaian doom',
      'post-doom metal',
      'dark jazz',
      'space rock',
      'british experimental',
      'retro metal',
      'post-metal',
      'power electronics',
      'north carolina metal',
      'funeral doom',
      'psychedelic doom',
      'dark ambient'],
 'pop rock': ['piano rock',
      'pop rock',
      'anthem worship',
      'ccm',
      'christian music',
      'deep ccm',
      'world worship',
      'worship',
      'christian alternative rock',
      'neo mellow',
      'viral pop',
      'acoustic pop',
      'idol',
      'indiecoustica',
      'roots worship'],
 'movie tunes': ['broadway', 'show tunes', 'movie tunes', 'hollywood', 'vintage broadway'],
 'classical': ['classical performance',
      'orchestral performance',
      'violin',
      'orchestra',
      'classical organ',
      'chamber orchestra',
      'choral',
      'classical piano'],
 'country': ['country rock',
      'country',
      'country dawn',
      'contemporary country',
      'country road',
      'modern country rock',
      'oklahoma country',
      'classic country pop',
      'redneck',
      'nashville sound',
      'country pop',
      'deep contemporary country',
      'country rap'],
 'new age': ['new age',
      'fingerstyle',
      'new age piano',
      'string folk',
      'harp',
      'christian relaxative',
      'a cappella',
      'lds',
      'operatic pop'],
 'latin': ['latin metal',
      'latin alternative',
      'latin rock',
      'mexican rock',
      'rock en espanol',
      'spanish pop',
      'rumba',
      'cantautor',
      'trova',
      'argentine rock',
      'spanish new wave',
      'rock nacional',
      'spanish punk',
      'euskal rock',
      'mexican indie'],
 37: ['dark wave',
      'ethereal wave',
      'gothic rock',
      'bow pop',
      'gothic americana',
      'cello',
      'medieval folk',
      'dark cabaret',
      'steampunk',
      'neoclassical darkwave'],
 'big band': ['adult standards',
      'lounge',
      'vocal jazz',
      'swing',
      'torch song',
      'contemporary vocal jazz',
      'tin pan alley',
      'brass band',
      'big band',
      'easy listening',
      'stride',
      'vintage jazz',
      'jazz trumpet',
      'swing revival',
      'new orleans jazz',
      'vintage gospel',
      'jazz trombone',
      'space age pop',
      'dixieland',
      'jazz orchestra',
      'jazz brass',
      'vocal harmony group'],
 'lo-fi': ['chillhop',
      'lo-fi beats',
      'jazz boom bap',
      'focus beats',
      'lo-fi jazzhop'],
 40: ['mexican son', 'son jarocho'],
 41: ['traditional soul', 'gospel soul'],
 'blues': ['blues',
      'blues rock',
      'electric blues',
      'modern blues',
      'texas blues',
      'modern blues rock',
      'power blues-rock',
      'louisiana blues',
      'acoustic blues',
      'chicago blues',
      'soul blues',
      'traditional blues',
      'harmonica blues',
      'piano blues',
      'boogie-woogie',
      'british blues',
      'country blues',
      'memphis blues',
      'new orleans blues',
      'jazz blues',
      'canadian blues',
      'harlem renaissance',
      'barrelhouse piano',
      'jug band',
      'piedmont blues',
      'deep delta blues',
      'pre-war blues',
      'delta blues'],
 'children': ['kindie rock', "children's folk", "children's music"],
 'african': ['afropop',
      'mande pop',
      'world',
      'azontobeats',
      'afrobeat',
      'nigerian pop',
      'afro dancehall'],
 'french': ['chanson',
      'nouvelle chanson francaise',
      'french rock',
      'francoton',
      'french pop',
      'french indie pop',
      'french hip hop',
      'pop urbaine',
      'rap francais'],
 46: ['funk carioca', 'sertanejo universitario'],
 47: ['filmi', 'desi pop', 'modern bollywood'],
 48: ['danish pop'],
 49: ['dutch pop', 'dutch rock'],
 50: ['cantopop',
      'mandopop',
      'taiwan pop',
      'c-pop',
      'classic mandopop',
      'classic cantopop'],
 51: ['jangle rock'],
 52: ['cajun', 'swamp pop', 'zydeco'],
 53: ['rhythm game'],
 'drum and bass': ['drum and bass',
      'jump up',
      'liquid funk',
      'uk dnb',
      'darkstep',
      'neurofunk',
      'stateside dnb',
      'jungle',
      'drumfunk',
      'deep dnb'],
 55: ['k-pop'],
 56: ['latin classical', 'tango', 'classical guitar', 'vintage tango'],
 57: ['spanish hip hop'],
 'smooth jazz': ['smooth jazz', 'smooth saxophone', 'deep smooth jazz'],
 'german': ['german rock',
      'liedermacher',
      'german pop',
      'classic schlager',
      'schlager',
      'ostrock',
      'partyschlager',
      'german hip hop'],
 60: ['europop',
      'vocal house',
      'disco house',
      'hardcore techno',
      'diva house',
      'eurodance',
      'hip house',
      'italian disco',
      'bubblegum dance',
      'acid house',
      'classic house',
      'deep house',
      'funky house',
      'garage house',
      'soulful house',
      'tribal house',
      'uk house'],
 61: ['twin cities indie', 'minneapolis indie'],
 62: ['vaporwave', 'future funk', 'hardvapour'],
 63: ['deep chill-out'],
 64: ['boy band',
      'hip pop',
      'contemporary r&b',
      'neo soul',
      'pop r&b',
      'quiet storm',
      'r&b',
      'urban contemporary',
      'soul',
      'trap queen',
      'motown',
      'classic soul',
      'disco',
      'funk',
      'southern soul',
      'memphis soul',
      'girl group',
      'freestyle',
      'minneapolis sound',
      'post-disco',
      'philly soul',
      'new jack swing',
      'northern soul',
      'souldies'],
 65: ['grave wave', 'minimal wave', 'dark post-punk'],
 66: ['classic opm', 'opm', 'pinoy rock'],
 67: ['musica tropical guatemalteca'],
 68: ['c86', 'tape club', 'seattle indie', 'twee pop', 'indie fuzzpop'],
 69: ['classic finnish pop',
      'classic iskelma',
      'finnish pop',
      'iskelma',
      'suomi rock',
      'finnish dance pop'],
 70: ['modern progressive rock',
      'neo-progressive',
      'symphonic rock',
      'progressive rock',
      'progressive metal',
      'crossover prog',
      'deep progressive rock'],
 71: ['deep vocal jazz'],
 72: ['sasscore',
      'mathcore',
      'gamecore',
      'nintendocore',
      'chaotic hardcore',
      'chiptune'],
 'bossa nova': ['bossa nova',
      'mpb',
      'samba',
      'brazilian indie',
      'nova mpb',
      'choro',
      'velha guarda'],
 74: ['new weird america',
      'drone folk',
      'free folk',
      'experimental psych',
      'deep neofolk'],
 75: ['hip hop quebecois',
      'auteur-compositeur-interprete quebecois',
      'chanson quebecois',
      'indie quebecois',
      'rock quebecois',
      'pop quebecois'],
 76: ['pop punk',
      'emo',
      'screamo',
      'bubblegrunge',
      'indie punk',
      'post-hardcore',
      'neon pop punk',
      'emo punk',
      'philly indie',
      'midwest emo',
      'chicago indie',
      'candy pop',
      'dreamo',
      'math rock',
      'alternative emo',
      'anthem emo',
      'norwegian pop',
      'diy emo',
      'indie emo rock',
      'pop emo',
      'progressive post-hardcore',
      'pixie'],
 77: ['classic dubstep',
      'uk bass',
      'glitch hop',
      'wonky',
      'future garage',
      'experimental bass'],
 78: ['classical',
      'early romantic era',
      'franco-flemish school',
      'renaissance',
      'late romantic era',
      'post-romantic era',
      'russian romanticism',
      'anglican liturgy',
      'baroque',
      'early music',
      'german baroque',
      'early modern classical',
      'impressionism',
      'italian romanticism',
      'neoclassicism',
      'italian baroque',
      'classical era',
      'german romanticism',
      'british modern classical',
      'french romanticism',
      'german opera',
      'operetta',
      'english renaissance',
      'galante era',
      'italian opera',
      'french baroque',
      'german renaissance',
      'madrigal',
      'french renaissance',
      'italian renaissance',
      'medieval'],
 79: ['klezmer']}


_metagenres_augmented = {
'indie rock/pop': ['art pop',
        'melancholia',
        'modern rock',
        'indie pop',
        'indie rock',
        'freak folk',
        'dream pop',
        'garage psych',
        'canadian indie',
        'modern alternative rock',
        'chillwave'],
    'soft vintage': ['adult standards',
        'lounge',
        'vocal jazz',
        'swing',
        'classic uk pop',
        'brill building pop',
        'bubblegum pop',
        'big band',
        'rock-and-roll',
        'easy listening',
        'stride'],
    'soft rock/pop': ['pop rock', 'neo mellow', 'acoustic pop', 'opm'],
    'r&b, soul, funk': ['hip pop',
        'contemporary r&b',
        'neo soul',
        'quiet storm',
        'r&b',
        'urban contemporary',
        'soul',
        'motown',
        'classic soul',
        'disco',
        'funk',
        'southern soul'],
    'punk': ['alternative rock',
        'punk',
        'skate punk',
        'experimental',
        'gbvfi',
        'post-punk',
        'punk blues',
        
        ###
        'uk post-punk'
    ],
    'rap & hip-hop': ['pop rap',
        'hip hop',
        'gangster rap',
        'rap',
        'dirty south rap',
        'southern hip hop',
        'trap',
        'vapor trap',
        'alternative hip hop',
        'east coast hip hop',
        'underground hip hop',
        'hardcore hip hop',
        'turntablism',
        'underground rap',
        
        ###
        'conscious hip hop',
        'political hip hop',
        'chicano rap',
        'west coast rap',
        'houston rap',
        'dirty south rap',
        'nyc rap',
        'queens hip hop',
        'atl hip hop',
        'melodic rap',
        'crunk',
        'deep southern trap',
        'dirty texas rap',
        'boom bap',
        'golden age hip hop',
        'old school hip hop',
        'dark trap',
        'jazz rap',
        'g funk',
        'hyphy',
        'oakland hip hop',
        'abstract hip hop',
        'bronx hip hop',
        'wu fam',
        'chicago rap',
        'miami hip hop',
        'cali rap',
        'minnesota hip hop',
        'west coast trap',
        'new jersey rap',
        'detroit hip hop',
        'battle rap',
        'scratch',
        'memphis hip hop',
        'sad rap',
        'experimental hip hop',
        'emo rap',
        'meme rap',
        'indie hip hop',
        'atl trap'
        
        ],
    'folk': ['folk',
        'roots rock',
        'singer-songwriter',
        'lilith',
        'indie folk',
        'alternative country',
        'texas country',
        'stomp and holler',
        'new americana',
        'deep new americana'
        
        ###
        'canadian singer-songwriter',
        'folk rock',
        'ectofolk',
        "women's music",
        'outlaw country',
        'austin singer-songwriter',
        'contemporary folk',
        'new americana',
        'alternative americana',
        'deep acoustic pop',
        'folk-pop',
        'american folk revival',
        'cosmic american',
        'canadian folk',
        'canadian indie',
        'modern folk rock',
        'toronto indie',
        'red dirt',
        'roots americana',
        'alternative roots rock',
        'new england americana',
        'canadian celtic',
        'michigan indie',
        'canadian americana',
        'quebec indie',
        'nl folk',
        'canadian country',
        'north carolina roots',
        'indie anthem-folk'    
    ],
    'classical': ['classical',
        'renaissance',
        'post-romantic era',
        'baroque',
        'early music',
        'early modern classical'
        
        ###
        'franco-flemish school',
        'late romantic era',
        'post-romantic era',
        'russian romanticism',
        'anglican liturgy',
        'german baroque',
        'impressionism',
        'italian romanticism',
        'neoclassicism',
        'italian baroque',
        'classical era',
        'german romanticism',
        'british modern classical',
        'french romanticism',
        'german opera',
        'operetta',
        'english renaissance',
        'galante era',
        'italian opera',
        'french baroque',
        'german renaissance',
        'madrigal',
        'french renaissance',
        'italian renaissance',    
    ],
    'show tunes': ['broadway', 'show tunes', 'hollywood'],
    'metal': ['alternative metal',
        'nu metal',
        'rap rock',
        'metal',
        'industrial metal',
        'death metal',
        'post-doom metal',

        ###
        'metal',
        'slayer',
        'speed metal',
        'us power metal',
        'voidgrind',
        'instrumental rock',
        'neo classical metal',
        'power metal',
        'shred',
        'death metal',
        'melodic death metal',
        'swedish death metal',
        'swedish metal',
        'technical death metal',
        'gothic symphonic metal',
        'black metal',
        'gothic metal',
        'symphonic black metal',
        'german metal',
        'melodic metal',
        'neo-trad metal',
        'symphonic metal',
        'brutal death metal',
        'florida death metal',
        'old school thrash',
        'crossover thrash',
        'thrash metal',
        'symphonic death metal',
        'atmospheric black metal',
        'usbm',
        'avant-garde metal',
        'deathrash',
        'finnish metal',
        'folk metal',
        'nwothm',
        'norwegian black metal',
        'norwegian metal',
        'pagan black metal',
        'black thrash',
        'dark black metal',
        'deathgrind',
        'grindcore',
        'jazz metal',
        'voidgaze',
        'post-black metal',
        'progressive jazz fusion',
        'symphonic power metal',
        'nyc metal',
        'australian metal',
        'death doom',
        'cavernous death metal',
        'black death'
    ],
    'edm': ['vocal house',
        'edm',
        'future bass',
        'pop edm',
        'disco house',
        'melodic dubstep',
        'electro house',
        'deep house',
        'house',
        'pop dance',
        'tropical house',
        'progressive house',
        'gaming edm',
        'dubstep',
        'gaming dubstep',
        'electronic trap',
        
        ###
        'classic dubstep',
        'uk bass',
        'glitch hop',
        'wonky',
        'future garage',
        'experimental bass',
        
        ],
    'metalcore': ['pop punk',
        'emo',
        'screamo',
        'bubblegrunge',
        'indie punk',
        'post-hardcore',
        'melodic metalcore',
        'metalcore',
        'dreamo'],
    'new wave': ['europop',
        'new wave pop',
        'permanent wave',
        'new wave',
        'new romantic',
        'synthpop'],
    'rock': ['rock',
        'album rock',
        'classic rock',
        'mellow gold',
        'soft rock',
        'hard rock',
        'art rock',
        'symphonic rock',
        'glam metal',
        'psychedelic rock'
        
        ###
        'modern progressive rock',
        'neo-progressive',
        'symphonic rock',
        'progressive rock',
        'progressive metal',
        'crossover prog',
        'deep progressive rock'

        ###
        'yacht rock',
        'new wave pop',
        'classic canadian rock',
        'dance rock',
        'experimental',
        'experimental rock',
        'noise rock',
        'new romantic',
        'heartland rock',
        'sleaze rock',
        'modern hard rock',
        'deep soft rock',
        'beatlesque',
        'melodic hard rock',
        'glam rock',
        'noise punk'
        ],
    'contemporary classical': ['american contemporary classical',
        'contemporary classical',
        'avant-garde',
        '21st century classical'],
    'alternative r&b':  # chilled indie pop and modern jazz 
        ['escape room', 'alternative r&b', 'indie soul'],  # https://www.thefader.com/2020/12/02/escape-room-genre-spotify-unwrapped-explanation-every-noise-glenn-mcdonald
    'techno': ['alternative dance',
        'electronica',
        'microhouse',
        'minimal techno',
        'new rave',
        'tech house'

        ###
        'full on',
        'progressive psytrance',
        'psychedelic trance',
        'psychill',
        'deep ambient',
        'space ambient',
        'ambient psychill',
        'goa trance'

        ###
        'german electronica',
        'indie electronica',
        'german techno',
        'microhouse',   
        'minimal techno',
        'dub techno',
        'cologne electronic',
        'hamburg electronic',
        'minimal tech house',
        'techno',
        'organic house',
        'minimal dub',
        ],
    'drum and bass': [
        'drum and bass'
    
        ###
        'jump up',
        'liquid funk',
        'uk dnb',
        'darkstep',
        'neurofunk',
        'stateside dnb',
        'jungle',
        'drumfunk',
        'deep dnb'
    ],
    'african': [
        'afropop'

        ###
        'mande pop',
        'world',
        'azontobeats',
        'afrobeat',
        'nigerian pop',
        'afro dancehall'
    ],
    'christian': ['christian music', 'christian alternative rock'],
    'new age': ['new age', 'new age piano'],
    'latin': ['latin',
        'latin pop',
        'ranchera',
        'latin alternative',
        'rock en espanol',
        'tropical',
        'latin hip hop',
        'reggaeton'

        ##
        'mariachi',
        'regional mexican',
        'latin jazz',
        'mexican pop',
        'bolero',
        'latin arena pop',
        'salsa',
        'dominican pop',
        'trap latino',
        'salsa puertorriquena',
        'italian adult pop',
        'merengue',
        'musica tradicional cubana',
        'salsa international',
        'mexican rock-and-roll',
        'bachata',
        'cumbia',
        'reggaeton flow'
    ],
    'soundtrack': [
        'scorecore', 
        'soundtrack', 
        'video game music',

        ###
        'classic soundtrack',
        'british soundtrack',
        'hauntology',
        'theme',
        'light music',
        'epicore',
        'japanese vgm',
        'japanese classical',
        'indie game soundtrack',
        'library music'
    ],
    'blues': ['blues',
        'blues rock',
        'electric blues',
        'modern blues',
        'modern blues rock',
        'traditional blues'

        ###
        'texas blues',
        'power blues-rock',
        'louisiana blues',
        'acoustic blues',
        'chicago blues',
        'soul blues',
        'harmonica blues',
        'piano blues',
        'boogie-woogie',
        'british blues',
        'country blues',
        'memphis blues',
        'new orleans blues',
        'jazz blues',
        'canadian blues',
        'harlem renaissance',
        'barrelhouse piano',
        'jug band',
        'piedmont blues',
        'deep delta blues',
        'pre-war blues',
        'delta blues'    
    ],
    'reggae': ['dub', 'reggae', 'roots reggae', 'ska', 'lovers rock'],
    'jazz': ['jazz',
        'contemporary jazz',
        'jazz fusion',
        'smooth jazz',
        'jazz saxophone'

        ###
        'avant-garde jazz',
        'free improvisation',
        'free jazz',
        'japanese jazz',
        'electric bass',
        'jazz organ',
        'bebop',
        'hard bop',
        'jazz drums',
        'instrumental funk',
        'jazz funk',
        'modern funk',
        'afrofuturism',
        'jazz guitar',
        'jazz piano',
        'contemporary post-bop',
        'cool jazz',
        'jazz double bass',
        'jazz violin',
        'gypsy jazz',
        'swedish jazz',
        'modern jazz piano',
        'soul jazz',
        'jazz vibraphone',
        'ecm-style jazz',
        'spiritual jazz',
        'jazz trio',
        'rare groove'
    ],
    'country': [
        'country', 
        'contemporary country',
        'country road',

        ###
        'country rock',
        'country dawn',
        'modern country rock',
        'oklahoma country',
        'classic country pop',
        'redneck',
        'nashville sound',
        'country pop',
        'deep contemporary country',
        'country rap'
    ],
    'pop': [
        'dance pop', 
        'pop', 
        'post-teen pop', 
        'electropop', 
        'indie poptimism',

        ###
        'metropopolis',
        'social media pop',
        'austindie',
        'uk pop',
        'indietronica',
        'la indie',
        'shimmer pop',
        'la pop',
        'stomp pop',
        'alt z',
        'etherpop',
        'indie electropop'    
    ],
    'celtic': [
        'celtic', 
        'irish folk',

        ###
        'british folk',
        'bagpipe',
        'celtic rock',
        'jig and reel',
        'irish neo-traditional',
        'scottish folk',
        'irish fiddle',
        'traditional irish singing',
        'uilleann pipes',
        'shanty',
        'traditional british folk',
        'celtic punk'
    ],
    'bluegrass': ['appalachian folk',
        'banjo',
        'bluegrass',
        'old-time',
        'progressive bluegrass'],
    'lo-fi': [
        'chillhop', 
        'lo-fi beats',

        ###
        'breakbeat',
        'trip hop',
        'downtempo',
        'nu skool breaks',
        'chill lounge',  
    ],
    'ambient': [
        'ambient', 
        'compositional ambient'
    
        ###
        'nu age',
        'glitch',
        'drone',
        'sound art',
        'compositional ambient',
        'fourth world',
        'new isolationism',
        'warm drone',
        'american post-rock',
        'drift',
        'j-ambient',
        'instrumental post-rock',
        'experimental ambient',
        'neo-classical',
        'mandible',
        'deconstructed club'
    ]
}


_metagenres_rev = reverse_dict(_metagenres)
_metagenres_fine_rev = reverse_dict(_metagenres_fine)
_metagenres_augmented_rev = reverse_dict(_metagenres_augmented)


def get_metagenre(genre):
    return _metagenres_augmented_rev.get(genre, 'unknown')


def get_majority_metagenre(genres):
    metagenres = [get_metagenre(genre) for genre in genres]
    metagenres = [genre for genre in metagenres if genre != 'unknown']
    if len(metagenres) == 0:
        return 'unknown'
    counter = collections.Counter(metagenres)
    return counter.most_common(1)[0][0]